### ISSUE TITLE
USB_CDC packaging

### ISSUE THREAD

**Issue by marwaneltoukhy** [ulixxe/usb_cdc#3]
Hello,

We're working on [IPM](https://github.com/efabless/IPM/tree/main), an open-source IPs Package Manager; it is meant to provide a mean for distributing high quality open-source IPs.

We wanted to package this IP to be part of IPM's growing database, we created [a fork](https://github.com/efabless/usb_cdc), to create the directory structure that IPM expects, and the config file for IPM as well. If you are interested we'd like you to maintain this repo. As you can see in the [config json file](https://github.com/efabless/usb_cdc/blob/main/usb_cdc.json), we are giving you full credit of your IP, IPM is just a means to distribute high quality opensource IPs.

**Comment by ulixxe** [comment]
Hi,
I am glad to know you want to include my IP in your Package Manager.
Is the fork already in line with your Package structure or does it need some effort to comply with your Package Manager?

I am available to maintain it, but right now I don't have much time to work on it.

**Comment by ulixxe** [comment]
I would like to update your fork to the latest version of usb_cdc, but I don't know how to do it.
