### ISSUE TITLE
I linked to this page 

### ISSUE THREAD

**Issue by PythonLinks** [ulixxe/usb_cdc#5]
From the Unofficial Mecrisp Ice Documentation Page. 
https://mecrisp-ice.readthedocs.io/en/latest/links.html

A reciprocal link would be most appreciated. 

What I would find most interesting is if you could shrink it down, by using a Mecrisp Ice Forth core as the control logic.  I did something similar for SPI.  

Here is an invite to the Pico-Ice discord server Forth channel. 
https://discord.gg/K8sWQUAn

Warm Regards
Christopher Lozinski

**Comment by ulixxe** [comment]
Hi Christopher,

Thank you for your suggestion.

The purpose of usb_cdc is to use only LUTs without RAM/ROM. I estimate a reduction of about 30% in LUTs if some parts are implemented with a small CPU. However, in this case, it is necessary to use RAM and ROM to make it work. This CPU is dedicated to the USB interface only and is not usable for other purposes. Therefore, some of the RAM/ROM resources cannot be used by the main CPU that uses usb_cdc as a USB interface.

Sorry, but I prefer not to add external links to avoid polluting the README file.
